# Generated by Django 4.0.1 on 2022-02-28 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0007_alter_advertisingspace_advertising_space_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is confirmed')),
                ('owner_decline', models.BooleanField(default=False, verbose_name='Owner decline order')),
                ('date_from', models.DateField(default=django.utils.timezone.now, verbose_name='Date from')),
                ('date_to', models.DateField(default=django.utils.timezone.now, verbose_name='Date to')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('advertising_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisingspace', verbose_name='Advertising space id')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Client id')),
            ],
        ),
    ]
