# Generated by Django 4.0.1 on 2022-02-19 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_birthday',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(19)], verbose_name='Date of birth'),
        ),
    ]
