# Generated by Django 4.0.1 on 2022-02-19 15:20

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_person_date_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_birthday',
            field=models.DateField(validators=[users.utils.no_future_date], verbose_name='Date of birth'),
        ),
    ]
