# Generated by Django 3.2.9 on 2021-12-04 17:29

import advertisements.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('data', models.JSONField(verbose_name='Data')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingSpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingSpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=advertisements.models.path_and_rename, verbose_name='Image')),
                ('advertising_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advertisements.advertisingspace', verbose_name='Adverting space')),
            ],
        ),
        migrations.AddField(
            model_name='advertisingspace',
            name='advertising_space_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advertisements.advertisingspacetype', verbose_name='Advertising space type'),
        ),
    ]
