# Generated by Django 3.2.9 on 2021-11-25 18:28

import advertisements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisingspaceimage',
            old_name='adverting_space',
            new_name='advertising_space',
        ),
        migrations.AlterField(
            model_name='advertisingspaceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=advertisements.models.path_and_rename, verbose_name='Image'),
        ),
    ]
