# Generated by Django 4.0.1 on 2022-01-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_advertisingspace_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingspaceimage',
            name='advertising_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='advertisements.advertisingspace', verbose_name='Adverting space'),
        ),
    ]
