# Generated by Django 4.0.1 on 2022-02-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisingspaceimage_advertising_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingspaceimage',
            name='advertising_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisements.advertisingspace', verbose_name='Adverting space'),
        ),
    ]
