# Generated by Django 4.0.1 on 2022-02-19 14:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0006_alter_advertisingspaceimage_advertising_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingspace',
            name='advertising_space_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisingspacecategory', verbose_name='Advertising space type'),
        ),
        migrations.AlterField(
            model_name='advertisingspace',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='advertisingspace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User id'),
        ),
    ]
